# Generated by Django 2.1.2 on 2018-10-09 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=64)),
                ('summary', models.TextField(max_length=10000)),
                ('is_employee', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company1', to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-submission_date'],
            },
        ),
    ]
